---
- hosts: localhost
  gather_facts: no
  pre_tasks:
    - add_host:
        name: "{{ router_ip }}"
        groups: routers
- hosts: routers
  gather_facts: no
  serial: 1
  connection: paramiko
  user: admin
  roles:
    - roles/beep
    - roles/dns/dhcp-lease
  vars_prompt:
    - name: "local_domain"
      prompt: "Local domain"
      confirm: no
      private: no
      default: local
    - name: "update_interval"
      prompt: "Update Interval (minutes)"
      confirm: no
      private: no
      default: 5
