---
- hosts: localhost
  gather_facts: no
#  vars_prompt:
#    - name: "router_host"
#      prompt: "Router ip address"
#      private: no
#  tasks:
#    - add_host:
#        name: "{router_host}"
#        groups: routers
- hosts: routers
  gather_facts: no
  serial: 1
  connection: paramiko
  user: admin
#  pre_tasks:
#    - name: Beep (check)
#      raw: /beep frequency=500
#      args: { executable: False }
#      register: last_output
#      failed_when: "'bad command' in '{{ last_output.stdout }}' or 'invalid value' in '{{ last_output.stdout }}' or 'expected end of command' in '{{ last_output.stdout }}'" 
  vars:
    opendns_host: 'Mikrotik'
  vars_prompt:
    - name: "opendns_email"
      prompt: "OpenDNS Email"
      confirm: no
      private: no
    - name: "opendns_password"
      prompt: "OpenDNS Password"
      confirm: yes
      private: yes
  roles:
    - roles/dns/disallow-remote
    - roles/dns/opendns
