---
- name: "Set external servers to: 8.8.8.8,8.8.4.4 (GOOGLE)"
  raw: /ip dns set servers=8.8.8.8,8.8.4.4
  args: { executable: False }
  register: last_output
  failed_when: "'bad command' in '{{ last_output.stdout }}' or 'invalid value' in '{{ last_output.stdout }}' or 'expected end of command' in '{{ last_output.stdout }}'" 
  
